Repository bkach/truco, pull requests merged in 2020-05, with the labels that each got.

#8 Edit ReadMe
  README.md
Labels: documentation

#9 Update deploy script
  scripts/deploy.sh
Labels: backend

#10 Add content type application/json
  handlers/util/buildHandler.go
Labels: backend

#11 Update games return value
  .idea/dictionaries/boriskach.xml
  go.mod
  go.sum
  handlers/createGame.go
  handlers/createPlayer.go
  handlers/dealCards.go
  handlers/deletePlayer.go
  handlers/playCard.go
  handlers/status.go
  truco/actions.go
  truco/game_test.go
Labels: backend

#13 Fix playing card multiple times bug
  truco/actions.go
  truco/game_test.go
Labels: backend, bug

#12 Add socket connections
  .idea/dictionaries/boris.xml
  go.mod
  go.sum
  handlers/getGamesSocket.go
  routers/routes.go
  truco/actions.go
  truco/game_test.go
  truco/globalState.go
Labels: backend

#16 Add player and game list sockets
  handlers/createGame.go
  handlers/createPlayer.go
  handlers/dealCards.go
  handlers/deleteGame.go
  handlers/deletePlayer.go
  handlers/getGame.go
  handlers/getGames.go
  handlers/playCard.go
  handlers/sockets/getGameListSocket.go
  handlers/sockets/getPlayerListSocket.go
  handlers/util/buildHandler.go
  handlers/util/buildSocketHandler.go
  handlers/util/getQuery.go
  handlers/util/handlerLogger.go
  routers/routes.go
  truco/actions.go
  truco/card.go
  truco/game_test.go
  truco/globalState.go
  truco/listeners.go
Labels: backend

#7 Ethel/frontend reset
  frontend/.env
  frontend/.gitignore
  frontend/.prettierrc
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/GameList/index.js
  frontend/src/index.js
  frontend/src/lib/api/index.js
  frontend/src/lib/http/index.js
  frontend/yarn.lock
Labels: frontend
